import './globals.css'
import type {Metadata} from 'next'
import AppContextProvider from "@/components/AppContext";

export const metadata: Metadata = {
    title: 'KINA - Hyperplasma',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <AppContextProvider>{children}</AppContextProvider>
        </body>
        </html>
    )
}
